<?php

namespace App\Livewire\LegalEntity;

use Log;
use Exception;
use Illuminate\Support\Arr;
use App\Models\Employee\Employee;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use App\Models\LegalEntity as LegalEntityModel;

class EditLegalEntity extends LegalEntity
{
    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        $this->getLegalEntityForm();
    }

    /**
     * Retrieves the legal entity form data.
     */
    protected function getLegalEntityForm(): void
    {
        parent::getLegalEntity(); // Call the parent method to retrieve basic legal entity data
        $this->getLicenseForm(); // Get the license form data
        $this->getArchiveForm(); // Get the archive form data
        $this->getOwnerLegalEntity(); // Get the owner's legal entity data
        $this->getAccreditationForm(); // Get the accreditation form data status
    }

    /**
     * Retrieves and sets only specific fields related to the license from the legal entity form.
     */
    protected function getLicenseForm(): void
    {
        $license = $this->legalEntity->licenses()?->first();

        if ($license) {
            $this->legalEntityForm->license = Arr::only($this->convertArrayKeysToCamelCase($license->toArray()),
            [
                'type',
                'licenseNumber',
                'issuedBy',
                'issuedDate',
                'expiryDate',
                'activeFromDate',
                'whatLicensed',
                'orderNo'
            ]);
        }
    }

    /**
     * Retrieves and formats specific fields from the archive form.
     */
    protected function getArchiveForm(): void
    {
        // Extracting only 'date' and 'place' fields from the first element of the archive
        if (!empty($this->legalEntityForm->archive)) {
            // if the legal entity has an archive, the 'archivationShow' property is set to true
            $this->legalEntityForm->archivationShow = true;

            $this->legalEntityForm->archive = Arr::only($this->legalEntityForm->archive[0],
                [
                    'date',
                    'place',
                ]
            );
        }
    }

    /**
     * Get the accreditation status of the legal entity
     * (if the legal entity has an accreditation, the 'accreditationShow' property is set to true)
     *
     * @return void
     */
    protected function getAccreditationForm(): void
    {
        if (!empty($this->legalEntityForm->accreditation)) {
            $this->legalEntityForm->accreditationShow = true;
        }
    }

    protected function getOwnerLegalEntity(): void
    {
        $owner = $this->legalEntity->getOwner();

        if (!$owner->exists()) {
            return;
        }

        $ownerData = $this->prepareOwnerData($owner);

        $this->legalEntityForm->owner = array_merge($this->legalEntityForm->owner ?? [], $ownerData);
    }

    private function prepareOwnerData(Employee $owner): array
    {
        $ownerData = $owner->party->toArray() ?? [];

        $ownerData['documents'] = $this->prepareDocumentsData($ownerData['documents']);
        $ownerData['position'] = $owner->position;
        $ownerData['employee_id'] = $owner->uuid;

        return $ownerData;
    }

    private function prepareDocumentsData(array $documents): array
    {
        if (empty($documents)) {
            return [];
        }

        return $this->convertArrayKeysToCamelCase($documents[0]);
    }


    public function updateLegalEntity()
    {
        $this->legalEntityForm->onEditValidate();

        if ($this->getErrorBag()->isNotEmpty()) {
            $this->dispatchBrowserEvent('scroll-to-error');
        }

        $result = $this->signLegalEntity();

        $response = $result['response'];
        $data = $result['request'];

        try {
            /**
             * The code below is need to save new client_secret if ESOZ returns successfull response
             * Without it next login may be impossible!
             */
            $legalEntity = LegalEntityModel::where(['uuid' => $response['data']['id'] ])->first();

            $legalEntity->clientSecret = $response['urgent']['security']['client_secret'] ?? $response['urgent']['security']['secret_key'] ?? null;

            $legalEntity->save();
            $legalEntity->refresh();

            DB::transaction(function() use($response, $data) {
                $this->createOrUpdateLegalEntity($response);

                $user = Auth::user();

                try {
                    $this->createEmployeeRequest($this->legalEntity, $data, $response['urgent']['employee_request_id'], $user?->id ?? null);
                } catch (Exception $err) {
                    throw new Exception('Error: createEmployeeRequest: ' . $err->getMessage(), $err->getCode());
                }
            });
        } catch (Exception $err) {
            Log::error(__('forms.errors.update_data', [], 'en'), ['error' => $err->getMessage()]);

            $this->dispatchErrorMessage(__('forms.errors.update_data'));

            return null;
        }

        return Redirect::route('edit.legalEntities')->with('success', __('forms.update_successfull')) ?? null;
    }

    public function render()
    {
        return view('livewire.legal-entity.edit-legal-entity', ['isEdit' => true]);
    }
}
